/**
 * Bundles the in-page capture/scoring script (which imports the exact same
 * @relocator/core scoring code the benchmarks validate) into a TS source
 * string module. Must run before tsc and before playwright test.
 */
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));

const result = await build({
  entryPoints: [join(root, 'src/inpage/main.ts')],
  bundle: true,
  write: false,
  format: 'iife',
  target: 'es2020',
  minify: false,
});

const source = result.outputFiles[0].text;
const generated = `// Generated by build-inpage.mjs — do not edit.
export const INPAGE_BUNDLE: string = ${JSON.stringify(source)};
`;
writeFileSync(join(root, 'src/inpage-bundle.generated.ts'), generated);
console.log(`inpage bundle: ${(source.length / 1024).toFixed(1)}kB`);
