/**
 * PR-comment rendering (design §10.1/§10.3): the patch proposal as a
 * markdown body a human can judge in 30 seconds — diff, evidence, and
 * affected tests per patch. Pipe into `gh pr comment --body-file -`.
 */

import { relative } from 'node:path';
import type { PatchWarning } from './aggregate.js';
import type { FileEdit } from './codemod.js';

export function renderMarkdown(
  edits: readonly FileEdit[],
  warnings: readonly PatchWarning[],
  cwd: string = process.cwd(),
): string {
  const lines: string[] = [];
  lines.push('## 🔧 Relocator: selector patch proposals');
  lines.push('');
  if (edits.length === 0) {
    lines.push('_No auto-patchable healings in this run._');
  } else {
    lines.push(
      `Selectors below broke at runtime and were healed by the similarity engine. ` +
        `Applying these patches makes the fix permanent — review each and run ` +
        '`relocator-patch --write` (or apply manually).',
    );
  }
  for (const edit of edits) {
    const p = edit.proposal;
    const file = relative(cwd, edit.file);
    lines.push('');
    lines.push(`### \`${file}:${edit.line}\``);
    lines.push('');
    lines.push('```diff');
    lines.push(`-${edit.before.trim()}`);
    lines.push(`+${edit.after.trim()}`);
    lines.push('```');
    lines.push('');
    lines.push(
      `- **Evidence**: tier ${p.tier} heal, similarity ${(p.bestScore * 100).toFixed(0)}%, ` +
        `healed ${p.healCount}× across ${p.testIds.length} test(s)`,
    );
    lines.push(`- **Old locator**: \`${p.originalLocator}\``);
    lines.push(`- **New locator**: \`${p.adoptedLocator}\``);
  }
  if (warnings.length > 0) {
    lines.push('');
    lines.push('### ⚠ Needs human attention');
    lines.push('');
    for (const w of warnings) {
      const where = w.callsite ? ` (\`${relative(cwd, w.callsite.file)}:${w.callsite.line}\`)` : '';
      lines.push(`- \`${w.originalLocator}\`${where}: ${w.reason}`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('_Generated by [Relocator](https://github.com/yurihypnosis/playwright-healer) from healing audit events._');
  return lines.join('\n');
}
